import Head from 'next/head';
import Sidebar from '../../components/sidebar/Sidebar';
import styles from '../../styles/Admin.module.scss';
import Dashboard from '../../components/dashboard/Dashboard';

const admin = function () {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.admin}>
        <Sidebar />
        <Dashboard />
      </main>
    </>
  );
};

export default admin;
