/* eslint-disable react-hooks/rules-of-hooks */
import Head from 'next/head';
import AddCaseStudy from '../../../components/case-study/AddCaseStudy';
import Sidebar from '../../../components/sidebar/Sidebar';
import styles from '../../../styles/CaseStudies.module.scss';

const CaseStudy = function () {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.admin}>
        <Sidebar />
        <AddCaseStudy />
      </main>
    </>
  );
};

export default CaseStudy;
