import Head from 'next/head';
import Link from 'next/link';
import Logo from '../../components/logo/Logo';
import Button from '../../components/ui/button/Button';
import Input from '../../components/ui/input/Input';
import styles from '../../styles/Auth.module.scss';
import { useRouter } from 'next/router';
import { useRef } from 'react';

const Register = function () {
  const router = useRouter();
  const emailRef = useRef();
  const passwordRef = useRef();

  const formSubmitHandler = function (e) {
    e.preventDefault();

    const emailValue = emailRef.current.value;
    const passwordValue = passwordRef.current.value;

    if (
      emailValue.trim() === process.env.NEXT_ADMIN_USERNAME &&
      passwordValue === process.env.NEXT_ADMIN_PASSWORD
    ) {
      router.push('/admin');
    } else {
      alert('Incorrect Details');
    }
  };

  return (
    <>
      <Head>
        <title>Register - Posi</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.auth}>
        <div className={styles.auth__view}>
          <div className={styles.auth__logo}>
            <Link href='/auth' name='Posi' className={styles.auth__logo__link}>
              <a className={styles.auth__logo__link} name='Posi'>
                <Logo />
              </a>
            </Link>
          </div>
          <p className={styles.auth__paragraph}>Register to continue</p>
          <form
            action=''
            className={styles.auth__form}
            onSubmit={formSubmitHandler}
          >
            <div className={styles.auth__group}>
              <label htmlFor='email' className={styles.auth__label}>
                Email
              </label>
              <Input
                ref={emailRef}
                type='email'
                placeholder='bill.sanders@example.com'
                name='email'
                id='email'
                className={styles.auth__input}
              />
            </div>
            <div className={styles.auth__group}>
              <label htmlFor='password' className={styles.auth__label}>
                Password
              </label>
              <Input
                ref={passwordRef}
                type='password'
                placeholder='Password'
                name='password'
                id='password'
                className={styles.auth__input}
              />
            </div>
            <div className={styles['auth__button-box']}>
              <Button type='submit' className={styles.auth__button}>
                Register
              </Button>
            </div>
            <div className={styles['auth__button-box']}>
              <Link href='/auth'>
                <a name='Login' className={styles.auth__link}>
                  Login
                </a>
              </Link>
            </div>
          </form>
        </div>
      </main>
    </>
  );
};

export default Register;
