import Head from 'next/head';
import Header from '../components/layout/header/Header';
import Container from '../components/ui/container/Container';
import styles from '../styles/About.module.scss';

const About = function () {
  return (
    <>
      <>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main className={styles.about}>
          <Container>
            <Header />
          </Container>
          <Container>
            <h1 className={styles.about__heading}>ABOUT ME</h1>
          </Container>
        </main>
      </>
    </>
  );
};

export default About;
