import Head from 'next/head';
import Header from '../components/layout/header/Header';
import Container from '../components/ui/container/Container';
import { initFirebase } from '../firebase/firebase';
import FontLinks from '../utils/FontLinks';
import styles from '../styles/Home.module.scss';
import Intro from '../components/sections/intro/Intro';
import CaseStudies from '../components/sections/caseStudies/CaseStudies';

initFirebase();

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <FontLinks />
      </Head>
      <main className={styles.home}>
        <Container>
          <Header />
        </Container>
        <Intro />
        <CaseStudies />
      </main>
    </>
  );
}
